package com.sudiptapaul.bedrock.service;

import com.sudiptapaul.bedrock.exception.GuardrailServiceException;
import com.sudiptapaul.bedrock.model.GuardrailResult;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import software.amazon.awssdk.services.bedrockruntime.BedrockRuntimeClient;
import software.amazon.awssdk.services.bedrockruntime.model.ApplyGuardrailRequest;
import software.amazon.awssdk.services.bedrockruntime.model.ApplyGuardrailResponse;
import software.amazon.awssdk.services.bedrockruntime.model.GuardrailAction;
import software.amazon.awssdk.services.bedrockruntime.model.GuardrailAssessment;
import software.amazon.awssdk.services.bedrockruntime.model.GuardrailContentBlock;
import software.amazon.awssdk.services.bedrockruntime.model.GuardrailContentSource;
import software.amazon.awssdk.services.bedrockruntime.model.GuardrailTextBlock;

import java.util.List;

/**
 * Service that enforces AWS Bedrock Guardrail policies on both user input and model output.
 *
 * <p>Unlike {@link RagService}, guardrail checks are <b>not</b> wrapped in a circuit breaker.
 * A guardrail failure is a hard failure — if the guardrail API is unavailable, the request
 * must fail rather than proceeding unchecked. All SDK exceptions are wrapped in
 * {@link GuardrailServiceException} so the controller can return a safe error response.
 *
 * <p>Guardrail policies checked (in priority order):
 * <ol>
 *   <li>DENIED_TOPIC — topic policy blocked the content</li>
 *   <li>CONTENT_FILTER — hate, violence, or other content filter triggered</li>
 *   <li>WORD_FILTER — custom or managed word list matched</li>
 *   <li>PII — sensitive information (PII entity or regex) detected</li>
 *   <li>GROUNDING_FAILED — output only; contextual grounding score below threshold</li>
 * </ol>
 */
@Slf4j
@Service
public class GuardrailService {

    private static final String TRIGGER_DENIED_TOPIC    = "DENIED_TOPIC";
    private static final String TRIGGER_CONTENT_FILTER  = "CONTENT_FILTER";
    private static final String TRIGGER_WORD_FILTER     = "WORD_FILTER";
    private static final String TRIGGER_PII             = "PII";
    private static final String TRIGGER_GROUNDING       = "GROUNDING_FAILED";
    private static final String TRIGGER_NONE            = "NONE";

    private final BedrockRuntimeClient bedrockRuntimeClient;

    @Value("${bedrock.guardrail.id}")
    private String guardrailId;

    @Value("${bedrock.guardrail.version:1}")
    private String guardrailVersion;

    /**
     * Constructs a {@code GuardrailService} with the given Bedrock Runtime client.
     *
     * @param bedrockRuntimeClient AWS SDK v2 client for Bedrock Runtime operations
     */
    public GuardrailService(BedrockRuntimeClient bedrockRuntimeClient) {
        this.bedrockRuntimeClient = bedrockRuntimeClient;
    }

    // ── Public methods ────────────────────────────────────────────────────────

    /**
     * Applies the configured guardrail to a user's input before it is sent to the model.
     *
     * <p>Evaluates the text against topic, content, word, and PII policies.
     * If any policy triggers, the request should be rejected before reaching the
     * RAG pipeline or model invocation.
     *
     * @param userInput the raw text submitted by the user
     * @return {@link GuardrailResult} with {@code blocked=true} and trigger details
     *         if the guardrail intervened; {@code blocked=false} otherwise
     * @throws GuardrailServiceException if the Bedrock Guardrail API call fails
     */
    public GuardrailResult checkInput(String userInput) {
        log.debug("Applying guardrail to INPUT. guardrailId={}", guardrailId);
        GuardrailResult result = evaluate(userInput, GuardrailContentSource.INPUT, false);
        if (result.isBlocked()) {
            log.warn("Guardrail BLOCKED input. Trigger: {}, Reason: {}",
                    result.getTriggerType(), result.getTriggerReason());
        }
        return result;
    }

    /**
     * Applies the configured guardrail to the model's output before it is returned to the user.
     *
     * <p>Evaluates against the same policies as {@link #checkInput}, and additionally
     * checks the contextual grounding policy — if the model's response is not grounded
     * in the retrieved KB context, it is flagged as {@code GROUNDING_FAILED}.
     *
     * @param modelOutput the text response generated by the foundation model
     * @return {@link GuardrailResult} with {@code blocked=true} and trigger details
     *         if the guardrail intervened; {@code blocked=false} otherwise
     * @throws GuardrailServiceException if the Bedrock Guardrail API call fails
     */
    public GuardrailResult checkOutput(String modelOutput) {
        log.debug("Applying guardrail to OUTPUT. guardrailId={}", guardrailId);
        GuardrailResult result = evaluate(modelOutput, GuardrailContentSource.OUTPUT, true);
        log.debug("Guardrail OUTPUT check. Trigger: {}", result.getTriggerType());
        return result;
    }

    /**
     * Probes the guardrail with a harmless test string to verify availability.
     *
     * <p>Used by the health check endpoint to report guardrail reachability
     * without affecting normal traffic.
     *
     * @return {@code true} if the guardrail API responds without exception;
     *         {@code false} if any exception is thrown
     */
    public boolean isAvailable() {
        try {
            ApplyGuardrailRequest request = buildRequest("health check", GuardrailContentSource.INPUT);
            bedrockRuntimeClient.applyGuardrail(request);
            return true;
        } catch (Exception e) {
            log.warn("Guardrail availability check failed: {}", e.getMessage());
            return false;
        }
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Core evaluation logic shared by {@link #checkInput} and {@link #checkOutput}.
     *
     * <p>Calls the guardrail API and maps the response action and policy assessments
     * into a {@link GuardrailResult}. When {@code checkGrounding} is {@code true},
     * the contextual grounding policy is also inspected.
     *
     * @param text            the text to evaluate
     * @param source          {@code INPUT} or {@code OUTPUT}
     * @param checkGrounding  whether to include grounding policy in trigger detection
     * @return populated {@link GuardrailResult}
     * @throws GuardrailServiceException on any SDK exception
     */
    private GuardrailResult evaluate(String text, GuardrailContentSource source, boolean checkGrounding) {
        try {
            ApplyGuardrailResponse response =
                    bedrockRuntimeClient.applyGuardrail(buildRequest(text, source));

            if (response.action() == GuardrailAction.GUARDRAIL_INTERVENED) {
                String triggerType   = determineTriggerType(response, checkGrounding);
                String triggerReason = determineTriggerReason(response, triggerType);
                String maskedText    = extractMaskedText(response, text);

                return GuardrailResult.builder()
                        .blocked(true)
                        .maskedText(maskedText)
                        .triggerType(triggerType)
                        .triggerReason(triggerReason)
                        .build();
            }

            return GuardrailResult.builder()
                    .blocked(false)
                    .maskedText(text)
                    .triggerType(TRIGGER_NONE)
                    .triggerReason(null)
                    .build();

        } catch (Exception e) {
            throw new GuardrailServiceException(
                    "Guardrail API call failed for source=" + source + ": " + e.getMessage(), e);
        }
    }

    /**
     * Builds the {@link ApplyGuardrailRequest} for a given text and content source.
     *
     * @param text   the text to evaluate
     * @param source {@code INPUT} or {@code OUTPUT}
     * @return a fully constructed request ready for submission
     */
    private ApplyGuardrailRequest buildRequest(String text, GuardrailContentSource source) {
        return ApplyGuardrailRequest.builder()
                .guardrailIdentifier(guardrailId)
                .guardrailVersion(guardrailVersion)
                .source(source)
                .content(List.of(
                        GuardrailContentBlock.builder()
                                .text(GuardrailTextBlock.builder()
                                        .text(text)
                                        .build())
                                .build()))
                .build();
    }

    /**
     * Inspects the guardrail assessment to determine which policy triggered first.
     *
     * <p>Evaluation order: DENIED_TOPIC → CONTENT_FILTER → WORD_FILTER → PII
     * → GROUNDING_FAILED (output only). Returns the first match found across
     * all assessments.
     *
     * @param response        the guardrail API response
     * @param checkGrounding  when {@code true}, also checks contextual grounding policy
     * @return the trigger type string constant; never {@code null}
     */
    private String determineTriggerType(ApplyGuardrailResponse response, boolean checkGrounding) {
        for (GuardrailAssessment assessment : response.assessments()) {

            if (assessment.topicPolicy() != null
                    && assessment.topicPolicy().hasTopics()
                    && assessment.topicPolicy().topics().stream()
                            .anyMatch(t -> "BLOCKED".equalsIgnoreCase(t.actionAsString()))) {
                return TRIGGER_DENIED_TOPIC;
            }

            if (assessment.contentPolicy() != null
                    && assessment.contentPolicy().hasFilters()
                    && assessment.contentPolicy().filters().stream()
                            .anyMatch(f -> !"NONE".equalsIgnoreCase(f.actionAsString()))) {
                return TRIGGER_CONTENT_FILTER;
            }

            if (assessment.wordPolicy() != null
                    && (assessment.wordPolicy().hasCustomWords()
                            || assessment.wordPolicy().hasManagedWordLists())) {
                return TRIGGER_WORD_FILTER;
            }

            if (assessment.sensitiveInformationPolicy() != null
                    && (assessment.sensitiveInformationPolicy().hasPiiEntities()
                            || assessment.sensitiveInformationPolicy().hasRegexes())) {
                return TRIGGER_PII;
            }

            if (checkGrounding
                    && assessment.contextualGroundingPolicy() != null
                    && assessment.contextualGroundingPolicy().hasFilters()
                    && assessment.contextualGroundingPolicy().filters().stream()
                            .anyMatch(f -> "BLOCKED".equalsIgnoreCase(f.actionAsString()))) {
                return TRIGGER_GROUNDING;
            }
        }
        return "UNKNOWN";
    }

    /**
     * Extracts a human-readable reason for the triggered policy from assessment details.
     *
     * <p>Provides specific context per trigger type:
     * <ul>
     *   <li>DENIED_TOPIC — the name of the matched denied topic</li>
     *   <li>CONTENT_FILTER — the filter type (e.g. HATE, VIOLENCE)</li>
     *   <li>WORD_FILTER — whether a custom word or managed list matched</li>
     *   <li>PII — the PII entity type (e.g. EMAIL, PHONE)</li>
     *   <li>GROUNDING_FAILED — grounding score below threshold message</li>
     * </ul>
     *
     * @param response    the guardrail API response
     * @param triggerType the trigger type determined by {@link #determineTriggerType}
     * @return a descriptive reason string, or {@code null} if details are unavailable
     */
    private String determineTriggerReason(ApplyGuardrailResponse response, String triggerType) {
        for (GuardrailAssessment assessment : response.assessments()) {
            switch (triggerType) {

                case TRIGGER_DENIED_TOPIC:
                    if (assessment.topicPolicy() != null && assessment.topicPolicy().hasTopics()) {
                        return assessment.topicPolicy().topics().stream()
                                .filter(t -> "BLOCKED".equalsIgnoreCase(t.actionAsString()))
                                .map(t -> t.name())
                                .findFirst()
                                .orElse(null);
                    }
                    break;

                case TRIGGER_CONTENT_FILTER:
                    if (assessment.contentPolicy() != null && assessment.contentPolicy().hasFilters()) {
                        return assessment.contentPolicy().filters().stream()
                                .filter(f -> !"NONE".equalsIgnoreCase(f.actionAsString()))
                                .map(f -> f.typeAsString())
                                .findFirst()
                                .orElse(null);
                    }
                    break;

                case TRIGGER_WORD_FILTER:
                    if (assessment.wordPolicy() != null) {
                        if (assessment.wordPolicy().hasCustomWords()) return "Custom word match";
                        if (assessment.wordPolicy().hasManagedWordLists()) return "Managed word list match";
                    }
                    break;

                case TRIGGER_PII:
                    if (assessment.sensitiveInformationPolicy() != null) {
                        if (assessment.sensitiveInformationPolicy().hasPiiEntities()) {
                            return assessment.sensitiveInformationPolicy().piiEntities().stream()
                                    .map(e -> e.typeAsString())
                                    .findFirst()
                                    .orElse(null);
                        }
                    }
                    break;

                case TRIGGER_GROUNDING:
                    return "Contextual grounding score below configured threshold";

                default:
                    break;
            }
        }
        return null;
    }

    /**
     * Extracts the masked or replacement text from guardrail outputs.
     *
     * <p>When a guardrail applies PII anonymisation or word masking, the output
     * contains the sanitised version of the original text. Falls back to the
     * original text if no output is present.
     *
     * @param response     the guardrail API response
     * @param originalText the original input text, used as fallback
     * @return the masked text from outputs, or {@code originalText} if outputs are absent
     */
    private String extractMaskedText(ApplyGuardrailResponse response, String originalText) {
        if (response.hasOutputs() && !response.outputs().isEmpty()) {
            return response.outputs().get(0).text();
        }
        return originalText;
    }
}
